# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server.ui'
#
# Created: Fri Feb 27 17:24:55 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(918, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 901, 531))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.formLayoutWidget = QtGui.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(560, 40, 160, 71))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.serverIp = QtGui.QLineEdit(self.formLayoutWidget)
        self.serverIp.setObjectName(_fromUtf8("serverIp"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.serverIp)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.serverPort = QtGui.QLineEdit(self.formLayoutWidget)
        self.serverPort.setObjectName(_fromUtf8("serverPort"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.serverPort)
        self.run = QtGui.QPushButton(self.tab)
        self.run.setGeometry(QtCore.QRect(650, 150, 71, 27))
        self.run.setObjectName(_fromUtf8("run"))
        self.textEdit = QtGui.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(50, 210, 831, 281))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.tab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(100, 10, 231, 182))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_11 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.name = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.name.setObjectName(_fromUtf8("name"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.name)
        self.temp = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.temp.setObjectName(_fromUtf8("temp"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.temp)
        self.bpd = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.bpd.setObjectName(_fromUtf8("bpd"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.bpd)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_10)
        self.bps = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.bps.setObjectName(_fromUtf8("bps"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.bps)
        self.campId = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.campId.setObjectName(_fromUtf8("campId"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.campId)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_12 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_13)
        self.pulse = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.pulse.setObjectName(_fromUtf8("pulse"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.pulse)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.table = QtGui.QTableWidget(self.tab_2)
        self.table.setEnabled(True)
        self.table.setGeometry(QtCore.QRect(0, 0, 881, 481))
        self.table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table.setObjectName(_fromUtf8("table"))
        self.table.setColumnCount(9)
        self.table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(8, item)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(72, 50, 34, 27))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.thBpSystolic = QtGui.QDial(self.tab_3)
        self.thBpSystolic.setGeometry(QtCore.QRect(721, 310, 111, 101))
        self.thBpSystolic.setMinimum(140)
        self.thBpSystolic.setMaximum(300)
        self.thBpSystolic.setNotchesVisible(True)
        self.thBpSystolic.setObjectName(_fromUtf8("thBpSystolic"))
        self.line_3 = QtGui.QFrame(self.tab_3)
        self.line_3.setGeometry(QtCore.QRect(1, 30, 901, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.lineEdit_6 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(750, 220, 89, 27))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lPulseMin = QtGui.QLineEdit(self.tab_3)
        self.lPulseMin.setGeometry(QtCore.QRect(441, 50, 89, 27))
        self.lPulseMin.setObjectName(_fromUtf8("lPulseMin"))
        self.label_14 = QtGui.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(111, 10, 81, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(681, 220, 51, 27))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lTempMax = QtGui.QLineEdit(self.tab_3)
        self.lTempMax.setGeometry(QtCore.QRect(140, 220, 89, 27))
        self.lTempMax.setObjectName(_fromUtf8("lTempMax"))
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(672, 50, 51, 27))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_16 = QtGui.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(761, 10, 41, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.theBpDiastolic = QtGui.QDial(self.tab_3)
        self.theBpDiastolic.setGeometry(QtCore.QRect(721, 90, 111, 101))
        self.theBpDiastolic.setMaximum(60)
        self.theBpDiastolic.setNotchesVisible(True)
        self.theBpDiastolic.setObjectName(_fromUtf8("theBpDiastolic"))
        self.lBpd = QtGui.QLineEdit(self.tab_3)
        self.lBpd.setGeometry(QtCore.QRect(741, 50, 89, 27))
        self.lBpd.setObjectName(_fromUtf8("lBpd"))
        self.line_2 = QtGui.QFrame(self.tab_3)
        self.line_2.setGeometry(QtCore.QRect(621, 0, 20, 501))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.thTempMin = QtGui.QDial(self.tab_3)
        self.thTempMin.setGeometry(QtCore.QRect(111, 90, 111, 101))
        self.thTempMin.setMaximum(37)
        self.thTempMin.setNotchesVisible(True)
        self.thTempMin.setObjectName(_fromUtf8("thTempMin"))
        self.thPulseMax = QtGui.QDial(self.tab_3)
        self.thPulseMax.setGeometry(QtCore.QRect(410, 310, 111, 101))
        self.thPulseMax.setMinimum(90)
        self.thPulseMax.setMaximum(120)
        self.thPulseMax.setNotchesVisible(True)
        self.thPulseMax.setObjectName(_fromUtf8("thPulseMax"))
        self.thTempMax_2 = QtGui.QDial(self.tab_3)
        self.thTempMax_2.setGeometry(QtCore.QRect(111, 310, 111, 101))
        self.thTempMax_2.setMinimum(40)
        self.thTempMax_2.setNotchesVisible(True)
        self.thTempMax_2.setObjectName(_fromUtf8("thTempMax_2"))
        self.lTempMin = QtGui.QLineEdit(self.tab_3)
        self.lTempMin.setGeometry(QtCore.QRect(141, 50, 89, 27))
        self.lTempMin.setObjectName(_fromUtf8("lTempMin"))
        self.thPulseMin = QtGui.QDial(self.tab_3)
        self.thPulseMin.setGeometry(QtCore.QRect(410, 90, 111, 101))
        self.thPulseMin.setMaximum(60)
        self.thPulseMin.setNotchesVisible(True)
        self.thPulseMin.setObjectName(_fromUtf8("thPulseMin"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(372, 50, 34, 27))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(71, 220, 34, 27))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_17 = QtGui.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(451, 10, 31, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.line = QtGui.QFrame(self.tab_3)
        self.line.setGeometry(QtCore.QRect(314, 0, 20, 491))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.lPulseMax = QtGui.QLineEdit(self.tab_3)
        self.lPulseMax.setGeometry(QtCore.QRect(439, 220, 89, 27))
        self.lPulseMax.setObjectName(_fromUtf8("lPulseMax"))
        self.label_18 = QtGui.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(370, 220, 34, 27))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(370, 50, 34, 27))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionDelete_Table = QtGui.QAction(MainWindow)
        self.actionDelete_Table.setObjectName(_fromUtf8("actionDelete_Table"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Server", None))
        self.label.setText(_translate("MainWindow", "IP", None))
        self.serverIp.setText(_translate("MainWindow", "0.0.0.0", None))
        self.label_2.setText(_translate("MainWindow", "Port", None))
        self.serverPort.setText(_translate("MainWindow", "5000", None))
        self.run.setText(_translate("MainWindow", "Run", None))
        self.label_11.setText(_translate("MainWindow", "Name", None))
        self.label_10.setText(_translate("MainWindow", "Systolic", None))
        self.label_4.setText(_translate("MainWindow", "Camp ID", None))
        self.label_12.setText(_translate("MainWindow", "Temp", None))
        self.label_13.setText(_translate("MainWindow", "Diastolic", None))
        self.label_3.setText(_translate("MainWindow", "Pulse", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Settings", None))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "S.No", None))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Camp ID", None))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Temp", None))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Pulse", None))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "BPD", None))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "BPS", None))
        item = self.table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Date", None))
        item = self.table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Time", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Data", None))
        self.label_5.setText(_translate("MainWindow", "Min", None))
        self.lineEdit_6.setText(_translate("MainWindow", "40", None))
        self.lPulseMin.setText(_translate("MainWindow", "40", None))
        self.label_14.setText(_translate("MainWindow", "Temperature", None))
        self.label_15.setText(_translate("MainWindow", "Systolic", None))
        self.lTempMax.setText(_translate("MainWindow", "40", None))
        self.label_6.setText(_translate("MainWindow", "Diastolic", None))
        self.label_16.setText(_translate("MainWindow", "BP", None))
        self.lBpd.setText(_translate("MainWindow", "40", None))
        self.lTempMin.setText(_translate("MainWindow", "40", None))
        self.label_8.setText(_translate("MainWindow", "Max", None))
        self.label_17.setText(_translate("MainWindow", "Pulse", None))
        self.lPulseMax.setText(_translate("MainWindow", "40", None))
        self.label_18.setText(_translate("MainWindow", "Max", None))
        self.label_9.setText(_translate("MainWindow", "Min", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Threshold", None))
        self.actionDelete_Table.setText(_translate("MainWindow", "Delete Table", None))

